version: '3.8'

services:
  tokoplay-backend:
    container_name: "tokoplay-backend"
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - APP_PORT=5000
      - DATABASE_NAME=tokoplay
      - DATABASE_URL=mongodb://mongodb:27017/

  mongodb:
    container_name: "tokoplay-db"
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - tokoplay-db-vol:/data/db
    restart: always
volumes:
  tokoplay-db-vol: