openapi: 3.0.3
info:
  title: Tokopedia Play Clone API
  description: API Spec for Tokopedia Play Clone
  version: '1.0'
  contact:
    email: limglenaldin@gmail.com
servers:
  - url: http://localhost:5000/api/v1
    description: Development
paths:
  /videos:
    get:
      tags: ["Videos API"]
      summary: Get a list of videos
      parameters:
        - $ref: '#/components/parameters/videoSearchQuery'
      responses:
        '200':
          $ref: '#/components/responses/videosResponse'
    post:
      tags: ["Videos API"]
      summary: Store video data in a database
      requestBody:
        $ref: '#/components/requestBodies/videoRequestBody'
      responses:
        '201':
          $ref: '#/components/responses/videoResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
  /videos/{id}:
    parameters:
      - $ref: '#/components/parameters/videoIdParam'
    get:
      tags: ["Videos API"]
      summary: Get a single data of video
      responses:
        '200':
          $ref: '#/components/responses/videoResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
    put:
      tags: ["Videos API"]
      summary: Update video data
      requestBody:
        $ref: '#/components/requestBodies/videoRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/videoResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
    patch:
      tags: ["Videos API"]
      summary: Patch total view video data
      responses:
        '200':
          $ref: '#/components/responses/videoResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
    delete:
      tags: ["Videos API"]
      summary: Delete a single data of video from database
      responses:
        '200':
          $ref: '#/components/responses/successDeleteResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
  /videos/{id}/products:
    parameters:
      - $ref: '#/components/parameters/videoIdParam'
    get:
      tags: ["Videos API", "Products API"]
      summary: Get a list of products in a video
      responses:
        '200':
          $ref: '#/components/responses/productsResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
  /videos/{id}/comments:
    parameters:
      - $ref: '#/components/parameters/videoIdParam'
    get:
      tags: ["Videos API", "Comments API"]
      summary: Get a list of comments in a video
      responses:
        '200':
          $ref: '#/components/responses/commentsResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
    post:
      tags: ["Videos API", "Comments API"]
      summary: Store a comment in a database
      requestBody:
        $ref: '#/components/requestBodies/commentRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/commentResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
  /products:
    get:
      tags: ["Products API"]
      summary: Get a list of products
      responses:
        '200':
          $ref: '#/components/responses/productsResponse'
    post:
      tags: ["Products API"]
      summary: Store product data in a database
      requestBody:
        $ref: '#/components/requestBodies/productRequestBody'
      responses:
        '201':
          $ref: '#/components/responses/videoResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
  /products/{id}:
    parameters:
      - $ref: '#/components/parameters/productIdParam'
    get:
      tags: ["Products API"]
      summary: Get a single data of product
      responses:
        '200':
          $ref: '#/components/responses/productResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
    put:
      tags: ["Products API"]
      summary: Update product data
      requestBody:
        $ref: '#/components/requestBodies/productRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/productResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
    delete:
      tags: ["Products API"]
      summary: Delete a single data of product from database
      responses:
        '200':
          $ref: '#/components/responses/successDeleteResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
components:
  schemas:
    videoObj:
      type: object
      properties:
        _id:
          type: string
          example: "64bf8f8a7d935e54d3c33a6f"
        title:
          type: string
          example: "Tampil Keren ke Kantor"
        store:
          type: string
          example: "Press Play"
        thumbnail_url:
          type: string
          example: "https://i3.ytimg.com/vi/SMz7wrkP5fI/maxresdefault.jpg"
        video_url:
          type: string
          example: "https://www.youtube.com/watch?v=SMz7wrkP5fI&t=1s"
        total_view:
          type: integer
          example: 100
        created_at:
          type: string
          example: "2023-07-25T09:02:02.070Z"
        updated_at:
          type: string
          example: "2023-07-25T09:02:02.070Z"
    productObj:
      type: object
      properties:
        _id:
          type: string
          example: "64bfca671fabe1759e695652"
        video_id:
          type: string
          example: "64bf8f8a7d935e54d3c33a6f"
        title:
          type: string
          example: "KINETIC Lanyard Cardholder Wallet ID Card Name Tag Holder"
        link:
          type: string
          example: "https://www.tokopedia.com/pressplay/kinetic-lanyard-cardholder-wallet-id-card-name-tag-holder"
        image_url:
          type: string
          example: "https://images.tokopedia.net/img/cache/900/VqbcmM/2023/6/8/92ff2ae0-7d33-4eeb-bdac-4a195ea7bd60.jpg"
        price:
          type: integer
          example: 169000
        created_at:
          type: string
          example: "2023-07-25T09:02:02.070Z"
        updated_at:
          type: string
          example: "2023-07-25T09:02:02.070Z"
    commentObj:
      type: object
      properties:
        _id:
          type: string
          example: "64bfca671fabe1759e695652"
        video_id:
          type: string
          example: "64bf8f8a7d935e54d3c33a6f"
        username:
          type: string
          example: "John Doe"
        comment:
          type: string
          example: "Kak warnanya hanya hitam saja?"
        created_at:
          type: string
          example: "2023-07-25T09:02:02.070Z"
        updated_at:
          type: string
          example: "2023-07-25T09:02:02.070Z"
    baseResponseObj:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
  parameters:
    videoSearchQuery:
      in: query
      name: search
      schema:
        type: string
    videoIdParam:
      in: path
      name: id
      required: true
      schema:
        type: string
    productIdParam:
      in: path
      name: id
      required: true
      schema:
        type: string
  requestBodies:
    videoRequestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                example: "Tampil Keren ke Kantor"
              store:
                type: string
                example: "Press Play"
              thumbnail_url:
                type: string
                example: "https://i3.ytimg.com/vi/SMz7wrkP5fI/maxresdefault.jpg"
              video_url:
                type: string
                example: "https://www.youtube.com/watch?v=SMz7wrkP5fI&t=1s"
    productRequestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              video_id:
                type: string
                example: "64bf8f8a7d935e54d3c33a6f"
              title:
                type: string
                example: "KINETIC Lanyard Cardholder Wallet ID Card Name Tag Holder"
              link:
                type: string
                example: "https://www.tokopedia.com/pressplay/kinetic-lanyard-cardholder-wallet-id-card-name-tag-holder"
              image_url:
                type: string
                example: "https://images.tokopedia.net/img/cache/900/VqbcmM/2023/6/8/92ff2ae0-7d33-4eeb-bdac-4a195ea7bd60.jpg"
              price:
                type: integer
                example: 169000
    commentRequestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
                example: "John Doe"
              comment:
                type: string
                example: "Kak warnanya hanya hitam saja?"
  responses:
    videosResponse:
      description: Success Response of /videos routes
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/baseResponseObj'
              - type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/videoObj'
    videoResponse:
      description: Success Response of /videos routes
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/baseResponseObj'
              - type: object
                properties:
                  data:
                    type: string
                    example: "64bf8f8a7d935e54d3c33a6f"
    productsResponse:
      description: Success Response of /products routes
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/baseResponseObj'
              - type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/productObj'
    productResponse:
      description: Success Response of /products routes
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/baseResponseObj'
              - type: object
                properties:
                  data:
                    type: string
                    example: "64bf8f8a7d935e54d3c33a6f"
    commentsResponse:
      description: Success Response of /comments routes
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/baseResponseObj'
              - type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/commentObj'
    commentResponse:
      description: Success Response of /comments routes
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/baseResponseObj'
              - type: object
                properties:
                  data:
                    $ref: '#/components/schemas/commentObj'
    badRequestResponse:
      description: Response for HTTP 400 - Bad Request
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/baseResponseObj'
              - type: object
                properties:
                  error:
                    type: array
                    items:
                      type: string
    notFoundResponse:
      description: Response for HTTP 404 - Not Found
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/baseResponseObj'
              - type: object
                properties:
                  data:
                    type: object
    successDeleteResponse:
      description: Response for success delete data
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/baseResponseObj'
              - type: object
                properties:
                  data:
                    type: object